### ISSUE TITLE
CONTACT MEのメールアドレス変更したほうがよいのでは？

### ISSUE THREAD

**Issue by xsota** [gunmanias/gunmanias#3]

**Comment by akai1256** [comment]
メールアドレスの宛先の変更をしました。

_layoutsのフォルダmain.htmlの中のemailのセクションの所を
gmailのURLを貼り付けを行い。
config.ymlのemailの部分に自分gmailのアカウントを貼り付けました。

以上でメールアドレスの変更が完了しました。
